# Generated by Django 6.0.3 on 2026-03-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('poste', models.CharField(choices=[('agent_menage', 'Agent de ménage'), ('garde_malade', 'Garde malade'), ('agent_nettoyage', 'Agent de nettoyage'), ('placement', 'Placement'), ('autre', 'Autre')], default='agent_menage', max_length=50)),
                ('experience', models.CharField(blank=True, max_length=100)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('neighborhood', models.CharField(blank=True, max_length=200, verbose_name='Quartier/Adresse')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('en_mission', 'En mission'), ('disponible', 'Disponible')], default='disponible', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='agents/photos/')),
            ],
            options={
                'verbose_name': 'Agent / Profil',
                'verbose_name_plural': 'Agents / Profils',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
