# Generated by Django 6.0.3 on 2026-03-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='cin',
            field=models.CharField(blank=True, max_length=50, verbose_name='CIN'),
        ),
        migrations.AddField(
            model_name='agent',
            name='situation',
            field=models.CharField(blank=True, max_length=50, verbose_name='Situation familiale'),
        ),
    ]
