# Generated by Django 6.0.3 on 2026-03-24 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_cin_agent_situation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='notes',
        ),
        migrations.AddField(
            model_name='agent',
            name='attestation_file',
            field=models.FileField(blank=True, null=True, upload_to='agents/attestations/'),
        ),
        migrations.AddField(
            model_name='agent',
            name='avail_7_7',
            field=models.BooleanField(default=False, verbose_name='7 jours / 7'),
        ),
        migrations.AddField(
            model_name='agent',
            name='avail_day',
            field=models.BooleanField(default=False, verbose_name='Journée (7h-18h)'),
        ),
        migrations.AddField(
            model_name='agent',
            name='avail_emergencies',
            field=models.BooleanField(default=False, verbose_name='Disponible pour les urgences'),
        ),
        migrations.AddField(
            model_name='agent',
            name='avail_evening',
            field=models.BooleanField(default=False, verbose_name='Soirée (après 18h)'),
        ),
        migrations.AddField(
            model_name='agent',
            name='avail_holidays',
            field=models.BooleanField(default=False, verbose_name='Jours fériés'),
        ),
        migrations.AddField(
            model_name='agent',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='agent',
            name='can_read_write',
            field=models.BooleanField(default=False, verbose_name='Sait lire et écrire'),
        ),
        migrations.AddField(
            model_name='agent',
            name='cin_file',
            field=models.FileField(blank=True, null=True, upload_to='agents/cin/'),
        ),
        migrations.AddField(
            model_name='agent',
            name='corpulence',
            field=models.CharField(blank=True, max_length=100, verbose_name='Corpulence'),
        ),
        migrations.AddField(
            model_name='agent',
            name='education_level',
            field=models.CharField(blank=True, max_length=100, verbose_name="Niveau d'étude"),
        ),
        migrations.AddField(
            model_name='agent',
            name='experience_months',
            field=models.PositiveIntegerField(default=0, verbose_name='Expérience (mois)'),
        ),
        migrations.AddField(
            model_name='agent',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, verbose_name='Expérience (années)'),
        ),
        migrations.AddField(
            model_name='agent',
            name='gender',
            field=models.CharField(blank=True, choices=[('homme', 'Homme'), ('femme', 'Femme')], max_length=10, verbose_name='Sexe'),
        ),
        migrations.AddField(
            model_name='agent',
            name='has_children',
            field=models.BooleanField(default=False, verbose_name='A des enfants'),
        ),
        migrations.AddField(
            model_name='agent',
            name='health_issues',
            field=models.CharField(blank=True, max_length=255, verbose_name='Maladie / Handicap'),
        ),
        migrations.AddField(
            model_name='agent',
            name='marital_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='Situation matrimoniale'),
        ),
        migrations.AddField(
            model_name='agent',
            name='operator_notes',
            field=models.TextField(blank=True, verbose_name="Note de l'opérateur"),
        ),
        migrations.AddField(
            model_name='agent',
            name='physical_appearance',
            field=models.CharField(blank=True, max_length=100, verbose_name='Présentation physique'),
        ),
        migrations.AddField(
            model_name='agent',
            name='training_details',
            field=models.TextField(blank=True, verbose_name='Formation requise'),
        ),
        migrations.AddField(
            model_name='agent',
            name='type_profil',
            field=models.CharField(blank=True, max_length=100, verbose_name='Type de profil'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='city',
            field=models.CharField(blank=True, default='Casablanca', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='nationality',
            field=models.CharField(blank=True, default='Marocaine', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=200, verbose_name='Quartier'),
        ),
        migrations.CreateModel(
            name='AgentExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='agents.agent')),
            ],
        ),
    ]
