# Generated by Django 6.0.3 on 2026-03-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_remove_agent_notes_agent_attestation_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentexperience',
            name='duration_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='Depuis combien de temps ?'),
        ),
        migrations.AddField(
            model_name='agentexperience',
            name='has_allergies',
            field=models.BooleanField(default=False, verbose_name='Allergies produits ménagers'),
        ),
        migrations.AddField(
            model_name='agentexperience',
            name='tasks',
            field=models.JSONField(blank=True, default=list, verbose_name='Tâches'),
        ),
        migrations.AddField(
            model_name='agentexperience',
            name='work_locations',
            field=models.JSONField(blank=True, default=list, verbose_name='Lieux de travail'),
        ),
    ]
