# Generated by Django 6.0.3 on 2026-03-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_agentexperience_duration_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='poste',
            field=models.CharField(choices=[('femme_menage', 'Femme de ménage'), ('garde_malade', 'Garde malade'), ('auxiliaire_vie', 'Auxiliaire de vie'), ('nounou', 'Nounou'), ('autre', 'Autre')], default='femme_menage', max_length=50),
        ),
        migrations.AlterField(
            model_name='agent',
            name='statut',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('non_disponible', 'Non disponible')], default='disponible', max_length=20),
        ),
    ]
