# Generated by Django 6.0.3 on 2026-04-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_agent_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='fiche_antropometrique',
            field=models.FileField(blank=True, null=True, upload_to='agents/fiches_antropometriques/'),
        ),
    ]
