# Generated by Django 6.0.3 on 2026-04-22 21:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_agent_fiche_antropometrique'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
