# Generated by Django 6.0.3 on 2026-04-22 21:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_agent_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
