# Generated by Django 6.0.3 on 2026-05-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_alter_agent_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='active_photo',
            field=models.CharField(choices=[('photo', 'Photo 1'), ('photo2', 'Photo 2'), ('photo3', 'Photo 3')], default='photo', max_length=10),
        ),
        migrations.AddField(
            model_name='agent',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='agents/photos/'),
        ),
        migrations.AddField(
            model_name='agent',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='agents/photos/'),
        ),
    ]
