# Generated by Django 6.0.3 on 2026-05-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_agent_active_photo_agent_photo2_agent_photo3'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='is_blacklisted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Blacklisté'),
        ),
    ]
