# Generated by Django 6.0.3 on 2026-07-11 10:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0013_agentassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='allergy_animals',
            field=models.BooleanField(default=False, verbose_name='Allergie aux animaux'),
        ),
        migrations.AddField(
            model_name='agent',
            name='availability_calendar',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='agent',
            name='cin_verso_file',
            field=models.FileField(blank=True, null=True, upload_to='agents/cin/', verbose_name='CIN Verso'),
        ),
        migrations.AddField(
            model_name='agent',
            name='disponibilite_intervention',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('non_disponible', 'Non disponible'), ('occupee', 'Occupée (en mission)')], default='disponible', max_length=20, verbose_name="Disponibilité d'intervention"),
        ),
        migrations.AddField(
            model_name='agent',
            name='is_smoking',
            field=models.BooleanField(default=False, verbose_name='Fume'),
        ),
        migrations.AddField(
            model_name='agent',
            name='leave_end',
            field=models.DateField(blank=True, null=True, verbose_name='Fin de congé'),
        ),
        migrations.AddField(
            model_name='agent',
            name='leave_start',
            field=models.DateField(blank=True, null=True, verbose_name='Début de congé'),
        ),
        migrations.AddField(
            model_name='agent',
            name='recruiter_notes',
            field=models.TextField(blank=True, verbose_name='Remarque du recruteur'),
        ),
        migrations.AddField(
            model_name='agent',
            name='registration_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Date d'enregistrement"),
        ),
        migrations.AddField(
            model_name='agent',
            name='shoe_size',
            field=models.CharField(blank=True, max_length=10, verbose_name='Pointure de chaussures'),
        ),
        migrations.AddField(
            model_name='agent',
            name='standby_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de jours standby'),
        ),
        migrations.AddField(
            model_name='agent',
            name='standby_until',
            field=models.DateField(blank=True, null=True, verbose_name="Standby jusqu'au"),
        ),
        migrations.AlterField(
            model_name='agent',
            name='active_photo',
            field=models.CharField(choices=[('photo', 'Photo 1'), ('photo2', 'Photo 2')], default='photo', max_length=10),
        ),
        migrations.AlterField(
            model_name='agent',
            name='statut',
            field=models.CharField(choices=[('nouveau', 'Nouveau'), ('active', 'Active'), ('blacklist', 'Blacklisté'), ('stand_by', 'Stand by'), ('en_conge', 'En congé'), ('malade', 'Malade')], default='nouveau', max_length=20),
        ),
    ]
