# Generated by Django 6.0.3 on 2026-09-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0014_agent_allergy_animals_agent_availability_calendar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='categorie',
            field=models.CharField(blank=True, choices=[('interne', 'Interne'), ('externe', 'Externe')], default='externe', max_length=20, verbose_name='Catégorie'),
        ),
    ]
