# Generated by Django 6.0.3 on 2026-04-27 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_entreecaisse_operational_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreecaisse',
            name='type_mouvement',
            field=models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie'), ('alimentation', 'Alimentation de la caisse')], max_length=15),
        ),
    ]
