# Generated by Django 6.0.3 on 2026-06-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_entreecaisse_type_mouvement'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreecaisse',
            name='categorie',
            field=models.CharField(blank=True, choices=[('Encaissement client (auto)', 'Encaissement client (auto)'), ('Remise FM — espèces', 'Remise FM — espèces'), ('Dépôt commercial — espèces', 'Dépôt commercial — espèces'), ('Virement client reçu', 'Virement client reçu'), ('Autre entrée', 'Autre entrée'), ('Salaires (équipe agence)', 'Salaires (équipe agence)'), ('Paiement femmes de ménage', 'Paiement femmes de ménage'), ('Achat produits ménagers', 'Achat produits ménagers'), ('Achat matériel / équipement', 'Achat matériel / équipement'), ('Loyer & charges bureaux', 'Loyer & charges bureaux'), ('Publicité & Marketin', 'Publicité & Marketin')], default='', max_length=100),
        ),
    ]
