# Generated by Django 6.0.3 on 2026-06-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_entreecaisse_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreecaisse',
            name='caisse_type',
            field=models.CharField(choices=[('caisse', 'Caisse'), ('tresorerie', 'Trésorerie')], default='caisse', max_length=20),
        ),
    ]
