# Generated by Django 6.0.3 on 2026-04-22 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0009_remove_demande_is_validated_alter_demande_statut'),
        ('feedback', '0001_initial'),
        ('missions', '0002_mission_finance_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='demande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='demandes.demande'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='note_agence',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='note_intervenant',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='opt_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='mission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='missions.mission'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='note',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
