# Generated by Django 6.0.3 on 2026-05-04 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0006_client_assigned_commercial_client_phone_history'),
        ('demandes', '0013_demande_part_agence_demande_parts_repartition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('target', models.CharField(choices=[('Client', 'Client'), ('Profil', 'Profil')], max_length=20)),
                ('segment', models.CharField(choices=[('Tous', 'Tous'), ('Particulier', 'Particulier'), ('Entreprise', 'Entreprise')], default='Tous', max_length=20)),
                ('criteria', models.CharField(blank=True, max_length=255)),
                ('channel', models.JSONField(blank=True, default=list)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('broadcast_time_start', models.TimeField(blank=True, null=True)),
                ('broadcast_time_end', models.TimeField(blank=True, null=True)),
                ('broadcast_date', models.DateField(blank=True, null=True)),
                ('per_day_dest', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('programmee', 'Programmée'), ('envoyee', 'Envoyée'), ('annulee', 'Annulée')], default='brouillon', max_length=20)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('reduction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reduction_type', models.CharField(choices=[('pourcentage', 'Pourcentage (%)'), ('montant_fixe', 'Montant fixe (MAD)')], max_length=20)),
                ('segment', models.CharField(choices=[('tous', 'Tous'), ('particulier', 'Particulier'), ('entreprise', 'Entreprise'), ('nouveaux', 'Nouveaux')], max_length=20)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('active', 'Actif'), ('desactivee', 'Inactif'), ('expiree', 'Expiré')], default='brouillon', max_length=20)),
                ('customer_status', models.CharField(max_length=255)),
                ('services', models.JSONField(blank=True, default=list)),
                ('canaux', models.JSONField(blank=True, default=list)),
                ('message_promotionnel', models.TextField(blank=True)),
                ('uses', models.IntegerField(default=0)),
                ('generated_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommercialGesture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('gesture_type', models.CharField(choices=[('reduction_tarif', 'Réduction sur le tarif'), ('facturation_annulee', 'Facturation annulée'), ('intervention_gratuite', 'Intervention gratuite')], max_length=50)),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('cloture', 'Clôturé')], default='en_attente', max_length=20)),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tva_active', models.BooleanField(default=False)),
                ('reduction_type', models.CharField(choices=[('montant', 'Montant fixe'), ('pourcentage', 'Pourcentage (%)')], default='montant', max_length=20)),
                ('reduction_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_a_payer', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('part_profil', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('part_agence', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('motif', models.TextField(blank=True)),
                ('envoyer_message', models.BooleanField(default=False)),
                ('message_client', models.TextField(blank=True)),
                ('canal_diffusion', models.JSONField(blank=True, default=list)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestes_commerciaux', to='clients.client')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestes_crees', to=settings.AUTH_USER_MODEL)),
                ('demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestes_commerciaux', to='demandes.demande')),
            ],
        ),
    ]
