# Generated by Django 6.0.3 on 2026-05-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='segment',
            field=models.CharField(choices=[('tous', 'Tous'), ('particulier', 'Particulier'), ('entreprise', 'Entreprise')], default='tous', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='target',
            field=models.CharField(choices=[('client', 'Client'), ('profil', 'Profil')], max_length=20),
        ),
    ]
