# Generated by Django 6.0.3 on 2026-06-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_alter_campaign_segment_alter_campaign_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='promo_type',
            field=models.CharField(choices=[('simple', 'Simple'), ('bd', 'BD')], default='simple', max_length=20),
        ),
    ]
