# Generated by Django 6.0.3 on 2026-06-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_promocode_promo_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='limit_uses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promocode',
            name='one_use_per_client',
            field=models.BooleanField(default=False),
        ),
    ]
