# Generated by Django 6.0.3 on 2026-06-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_promocode_limit_uses_promocode_one_use_per_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='broadcasted',
            field=models.BooleanField(default=False),
        ),
    ]
