# Generated by Django 6.0.3 on 2026-03-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='client',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=200, verbose_name='Quartier'),
        ),
    ]
