# Generated by Django 6.0.3 on 2026-03-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_address_alter_client_neighborhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='avis_commercial',
            field=models.TextField(blank=True, verbose_name='Avis commercial'),
        ),
        migrations.AddField(
            model_name='client',
            name='avis_operationnel',
            field=models.TextField(blank=True, verbose_name='Avis opérationnel'),
        ),
    ]
