# Generated by Django 6.0.3 on 2026-04-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='opt_out_feedback',
            field=models.BooleanField(default=False, verbose_name='Désinscription Feedback'),
        ),
    ]
