# Generated by Django 6.0.3 on 2026-04-29 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_opt_out_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='assigned_commercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_geres', to=settings.AUTH_USER_MODEL, verbose_name='Commercial assigné (Owner)'),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_history',
            field=models.JSONField(blank=True, default=list, verbose_name='Historique des numéros'),
        ),
    ]
