# Generated by Django 6.0.3 on 2026-05-07 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_assigned_commercial_client_phone_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='clients.client')),
            ],
            options={
                'verbose_name': 'Historique Action Client',
                'verbose_name_plural': 'Historiques Actions Client',
                'ordering': ['-created_at'],
            },
        ),
    ]
