# Generated by Django 6.0.3 on 2026-05-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_clientactionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_blacklisted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Blacklisté'),
        ),
    ]
