# Generated by Django 6.0.3 on 2026-05-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('moderateur', 'Modérateur'), ('responsable_commercial', 'Responsable Commercial'), ('commercial', 'Commercial'), ('responsable_operations', 'Responsable des Opérations'), ('charge_operations', 'Chargée des Opérations'), ('operationnel', 'Opérationnel')], default='commercial', max_length=30),
        ),
    ]
