# Generated by Django 6.0.3 on 2026-05-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100, unique=True)),
                ('permissions', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Permission de Rôle',
                'verbose_name_plural': 'Permissions de Rôle',
            },
        ),
    ]
