# Generated by Django 6.0.3 on 2026-09-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_add_retirer_profil_demande_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('moderateur', 'Modérateur'), ('responsable_commercial', 'Responsable Commercial'), ('commercial', 'Commercial'), ('responsable_operations', 'Responsable des Opérations'), ('charge_operations', 'Chargée des Opérations'), ('operationnel', 'Opérationnel'), ('runner', 'Runner / Chauffeur Livreur'), ('responsable_linge', 'Responsable Linge / Blanchisserie'), ('client_conciergerie', 'Client Conciergerie')], default='commercial', max_length=30),
        ),
    ]
