# Generated by Django 6.0.3 on 2026-04-28 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_alter_agent_uuid'),
        ('missions', '0002_mission_finance_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='annulation_raison',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='delegue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions_deleguees', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='mission',
            name='intervenants',
            field=models.ManyToManyField(blank=True, related_name='missions_incluses', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='mission',
            name='montant_agence_doit_profil',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='mission',
            name='montant_profil_annulation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='mission',
            name='montant_profil_doit_agence',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='mission',
            name='profil_sera_paye',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mission',
            name='paiement_client_statut',
            field=models.CharField(choices=[('non_paye', 'Non payé'), ('en_attente', 'Paiement en attente'), ('effectue', 'Paiement effectué'), ('partiel', 'Paiement partiel'), ('agence_payee_client', 'Agence payée / Client'), ('profil_paye_client', 'Profil payé / Client'), ('facturation_annulee', 'Facturation annulée')], default='non_paye', max_length=20),
        ),
    ]
