# Generated by Django 6.0.3 on 2026-05-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0003_mission_annulation_raison_mission_delegue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='paiement_client_statut',
            field=models.CharField(choices=[('non_paye', 'Non payé'), ('en_attente', 'Paiement en attente'), ('effectue', 'Paiement effectué'), ('partiel', 'Paiement partiel'), ('agence_payee_client', 'Agence payée / Client'), ('profil_paye_client', 'Profil payé / Client'), ('facturation_annulee', 'Facturation annulée'), ('intervention_gratuite', 'Intervention gratuite')], default='non_paye', max_length=30),
        ),
    ]
