# Generated by Django 6.0.3 on 2026-06-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0005_alter_mission_paiement_client_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='paiement_client_statut',
            field=models.CharField(choices=[('non_paye', 'Non payé'), ('en_attente', 'Paiement en attente'), ('effectue', 'Paiement effectué'), ('partiel', 'Paiement partiel'), ('agence_payee_client', 'Agence payée / Client'), ('profil_paye_client', 'Profil payé / Client'), ('commercial_paye_client', 'Commercial payé / client'), ('facturation_annulee', 'Annulé'), ('intervention_gratuite', 'Intervention gratuite')], default='non_paye', max_length=30),
        ),
    ]
