# Generated by Django 6.0.3 on 2026-08-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='photo_acces',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Photo boîte à clés / digicode / accès'),
        ),
        migrations.AddField(
            model_name='bien',
            name='photo_principale',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Photo principale du logement'),
        ),
    ]
