# Generated by Django 6.0.3 on 2026-03-13 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=200)),
                ('segment', models.CharField(choices=[('particulier', 'Particulier'), ('entreprise', 'Entreprise')], default='particulier', max_length=20)),
                ('source', models.CharField(choices=[('site', 'Site web'), ('backoffice', 'Back-office')], default='site', max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('annule', 'Annulé'), ('termine', 'Terminé')], default='en_attente', max_length=20)),
                ('frequency', models.CharField(choices=[('oneshot', 'Une fois'), ('abonnement', 'Abonnement')], default='oneshot', max_length=20)),
                ('frequency_label', models.CharField(blank=True, max_length=100)),
                ('date_intervention', models.DateField(blank=True, null=True)),
                ('heure_intervention', models.CharField(blank=True, max_length=50)),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix')),
                ('is_devis', models.BooleanField(default=False, verbose_name='Sur devis')),
                ('mode_paiement', models.CharField(blank=True, choices=[('virement', 'Virement'), ('carte', 'Par carte'), ('cheque', 'Par chèque'), ('agence', "À l'agence"), ('sur_place', 'Sur place')], max_length=20)),
                ('statut_paiement', models.CharField(choices=[('non_paye', 'Non payé'), ('en_attente_paiement', 'Paiement en attente'), ('paye', 'Paiement effectué')], default='non_paye', max_length=30)),
                ('avance_paiement', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('formulaire_data', models.JSONField(blank=True, default=dict)),
                ('cao', models.BooleanField(default=False, verbose_name='Confirmation avant opération')),
                ('note_commercial', models.TextField(blank=True)),
                ('note_operationnel', models.TextField(blank=True)),
                ('avis_annulation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_assignees', to=settings.AUTH_USER_MODEL, verbose_name='Commercial assigné')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandes', to='clients.client')),
            ],
            options={
                'verbose_name': 'Demande',
                'verbose_name_plural': 'Demandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('devis', 'Devis PDF'), ('png', 'Récapitulatif PNG'), ('facture', 'Facture'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('fichier', models.FileField(upload_to='documents/%Y/%m/')),
                ('nom', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='demandes.demande')),
            ],
            options={
                'verbose_name': 'Document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NRPLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('commercial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nrp_logs', to='demandes.demande')),
            ],
            options={
                'verbose_name': 'NRP',
                'verbose_name_plural': 'NRPs',
                'ordering': ['-date'],
            },
        ),
    ]
