# Generated by Django 6.0.3 on 2026-03-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('virement', 'Virement'), ('cheque', 'Par chèque'), ('agence', "À l'agence"), ('sur_place', 'Sur place')], max_length=20),
        ),
        migrations.AlterField(
            model_name='demande',
            name='statut_paiement',
            field=models.CharField(choices=[('non_paye', 'Non payé'), ('acompte', 'Acompte versé'), ('partiel', 'Paiement partiel'), ('integral', 'Paiement intégral')], default='non_paye', max_length=30),
        ),
    ]
