# Generated by Django 6.0.3 on 2026-03-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0002_alter_demande_mode_paiement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='preference_horaire',
            field=models.CharField(blank=True, max_length=50, verbose_name='Préférence horaire'),
        ),
    ]
