# Generated by Django 6.0.3 on 2026-04-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_alter_agent_poste_alter_agent_statut'),
        ('demandes', '0003_demande_preference_horaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='profils_envoyes',
            field=models.ManyToManyField(blank=True, related_name='demandes_proposees', to='agents.agent', verbose_name='Profils envoyés'),
        ),
    ]
