# Generated by Django 6.0.3 on 2026-04-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0004_add_profils_envoyes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='statut_paiement',
            field=models.CharField(choices=[('non_paye', 'Non payé'), ('acompte', 'Acompte versé'), ('partiel', 'Paiement partiel'), ('integral', 'Payé')], default='non_paye', max_length=30),
        ),
    ]
