# Generated by Django 6.0.3 on 2026-04-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0005_alter_demande_statut_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'Nouveau besoin'), ('en_cours', 'Pres. en cours'), ('termine', 'Pres. terminée'), ('annule', 'Rejeté / Annulé'), ('facture_annulee', 'Facturation annulée')], default='en_attente', max_length=20),
        ),
    ]
