# Generated by Django 6.0.3 on 2026-04-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0006_alter_demande_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='is_validated',
            field=models.BooleanField(default=False, verbose_name="Validé par l'admin"),
        ),
        migrations.AlterField(
            model_name='demande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'Nouveau besoin'), ('en_cours', 'Pres. en cours'), ('termine', 'Pres. terminée'), ('annule', 'Rejeté / Annulé'), ('facture_annulee', 'Facturation annulée'), ('confirme_intervention', 'Confirmé intervention')], default='en_attente', max_length=40),
        ),
    ]
