# Generated by Django 6.0.3 on 2026-04-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0007_demande_is_validated_alter_demande_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='demande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'Nouveau besoin'), ('confirme_intervention', 'Confirmé intervention'), ('en_cours', 'Pres. en cours'), ('termine', 'Pres. terminée'), ('annule', 'Rejeté / Annulé'), ('facture_annulee', 'Facturation annulée')], default='en_attente', max_length=50),
        ),
    ]
