# Generated by Django 6.0.3 on 2026-04-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0008_alter_demande_is_validated_alter_demande_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='is_validated',
        ),
        migrations.AlterField(
            model_name='demande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('annule', 'Annulé'), ('termine', 'Terminé'), ('pres_en_cours', 'Pres. en cours'), ('pres_terminee', 'Pres. terminée')], default='en_attente', max_length=20),
        ),
    ]
