# Generated by Django 6.0.3 on 2026-04-22 21:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_alter_agent_uuid'),
        ('demandes', '0009_remove_demande_is_validated_alter_demande_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='agents.agent')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='demandes.demande')),
            ],
            options={
                'verbose_name': 'Partage de profil',
                'ordering': ['-created_at'],
            },
        ),
    ]
