# Generated by Django 6.0.3 on 2026-04-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0010_profilshare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='statut_paiement',
            field=models.CharField(choices=[('non_paye', 'Non payé'), ('acompte', 'Acompte versé'), ('partiel', 'Paiement partiel'), ('integral', 'Payé'), ('en_attente', 'Paiement en attente')], default='non_paye', max_length=30),
        ),
    ]
