# Generated by Django 6.0.3 on 2026-04-29 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_assigned_commercial_client_phone_history'),
        ('demandes', '0011_alter_demande_statut_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='identification_statut',
            field=models.CharField(choices=[('nouvelle', 'Nouvelle'), ('existant_valide', 'Client existe déjà'), ('verification_requise', 'Vérification requise')], default='nouvelle', max_length=30, verbose_name="Statut d'identification"),
        ),
        migrations.AddField(
            model_name='demande',
            name='potential_duplicate_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_suspectes', to='clients.client', verbose_name='Client potentiel (doublon)'),
        ),
    ]
