# Generated by Django 6.0.3 on 2026-04-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0012_demande_identification_statut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='part_agence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Part agence'),
        ),
        migrations.AddField(
            model_name='demande',
            name='parts_repartition',
            field=models.JSONField(blank=True, default=list, verbose_name='Répartition des parts'),
        ),
    ]
