# Generated by Django 6.0.3 on 2026-05-05 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_assigned_commercial_client_phone_history'),
        ('demandes', '0013_demande_part_agence_demande_parts_repartition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='clients.client'),
        ),
    ]
