# Generated by Django 6.0.3 on 2026-06-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0014_alter_demande_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('virement', 'Par virement'), ('cheque', 'Par chèque'), ('especes', 'En espèces'), ('carte', 'Par carte bancaire (solution de paiement en ligne)'), ('agence', "À l'agence"), ('sur_place', 'Sur place')], max_length=20),
        ),
        migrations.AlterField(
            model_name='demande',
            name='statut_paiement',
            field=models.CharField(choices=[('non_paye', 'Non payé'), ('acompte', 'Acompte versé'), ('partiel', 'Paiement partiel'), ('integral', 'Payé'), ('en_attente', 'Paiement en attente'), ('intervention_gratuite', 'Intervention gratuite'), ('facturation_annulee', 'Facturation annulée')], default='non_paye', max_length=30),
        ),
    ]
