# Generated by Django 6.0.3 on 2026-06-10 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0016_appnotification_subscriptionplanning'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='parent_demande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions_generees', to='demandes.demande', verbose_name="Demande d'abonnement parente"),
        ),
    ]
