# Generated by Django 6.0.3 on 2026-06-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0017_demande_parent_demande'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplanning',
            name='semaines',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
