# Generated by Django 6.0.3 on 2026-06-15 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0018_subscriptionplanning_semaines'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='assigned_to_operations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_operations', to=settings.AUTH_USER_MODEL, verbose_name='Chargé des opérations assigné'),
        ),
    ]
