# Generated by Django 6.0.3 on 2026-06-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0019_demande_assigned_to_operations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='statut_paiement',
            field=models.CharField(choices=[('non_paye', 'Non payé'), ('acompte', 'Acompte versé'), ('partiel', 'Paiement partiel'), ('integral', 'Payé'), ('en_attente', 'Paiement en attente'), ('intervention_gratuite', 'Intervention gratuite'), ('facturation_annulee', 'Annulé')], default='non_paye', max_length=30),
        ),
    ]
