# Generated by Django 6.0.3 on 2026-06-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0021_demande_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='devis_statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente_validation', 'En attente validation'), ('valide', 'Validé'), ('envoye', 'Envoyé'), ('accepte', 'Accepté'), ('refuse', 'Refusé / Expiré')], default='brouillon', max_length=30, verbose_name='Statut du devis'),
        ),
    ]
