# Generated by Django 6.0.3 on 2026-06-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0022_demande_devis_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeteReligieuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('aid_kebir', 'Aïd el Kébir'), ('aid_fitr', 'Aïd el Fitr'), ('mawlid', 'Mawlid Ennabawi')], max_length=20, verbose_name='Fête')),
                ('date', models.DateField(verbose_name='Date de la fête')),
                ('annee', models.IntegerField(verbose_name='Année')),
                ('jours_avant', models.PositiveIntegerField(default=1, verbose_name='Jours suspendus avant')),
                ('jours_apres', models.PositiveIntegerField(default=2, verbose_name='Jours suspendus après')),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fête religieuse',
                'verbose_name_plural': 'Fêtes religieuses',
                'ordering': ['date'],
                'unique_together': {('type', 'annee')},
            },
        ),
    ]
