# Generated by Django 6.0.3 on 2026-06-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0023_fetereligieuse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetereligieuse',
            name='type',
            field=models.CharField(max_length=100, verbose_name='Fête'),
        ),
    ]
