# Generated by Django 6.0.3 on 2026-06-25 02:38

from django.db import migrations, models


def convert_boolean_cao_to_string(apps, schema_editor):
    Demande = apps.get_model('demandes', 'Demande')
    Demande.objects.filter(cao='1').update(cao='oui')
    Demande.objects.filter(cao='0').update(cao='non')
    Demande.objects.filter(cao='True').update(cao='oui')
    Demande.objects.filter(cao='False').update(cao='non')
    Demande.objects.exclude(cao__in=['oui', 'non', 'reporte']).update(cao='non')


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0024_alter_fetereligieuse_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='cao',
            field=models.CharField(choices=[('non', 'Non'), ('oui', 'Oui'), ('reporte', 'Reporté')], default='non', max_length=20, verbose_name='Confirmation avant opération'),
        ),
        migrations.RunPython(convert_boolean_cao_to_string, migrations.RunPython.noop),
    ]
