# Generated by Django 6.0.3 on 2026-06-25 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0025_alter_demande_cao'),
        ('marketing', '0003_promocode_promo_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='marketing.promocode'),
        ),
    ]
