# Generated by Django 6.0.3 on 2026-08-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0026_demande_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplanning',
            name='nombre_passages_mois',
            field=models.IntegerField(default=0, help_text='Nombre de passages planifiés pour le mois en cours (calculé côté frontend)'),
        ),
    ]
