# Generated by Django 6.0.3 on 2026-08-05 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0027_add_nombre_passages_mois'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='montant_devis',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant du devis'),
        ),
        migrations.AddField(
            model_name='demande',
            name='montant_facture',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant de facture'),
        ),
    ]
