# Generated by Django 6.0.3 on 2026-09-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0028_demande_montant_devis_demande_montant_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('annule', 'Annulé'), ('termine', 'Terminé'), ('pres_confirmee', 'Prestation confirmée'), ('pres_en_cours', 'Pres. en cours'), ('pres_a_confirmer', 'Pres. à confirmer'), ('pres_terminee', 'Pres. terminée'), ('resilie', 'Résilié')], default='en_attente', max_length=20),
        ),
    ]
