# Generated by Django 6.0.3 on 2026-09-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0029_alter_demande_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('virement', 'Par virement'), ('cheque', 'Par chèque'), ('especes', 'En espèces'), ('carte', 'Par carte bancaire (solution de paiement en ligne)'), ('virement_especes', 'Virement / Espèce'), ('agence', "À l'agence"), ('sur_place', 'Sur place')], max_length=30),
        ),
    ]
