# Generated by Django 6.0.3 on 2026-09-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0030_alter_demande_mode_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('virement_ag', 'Virement Ag'), ('virement_com', 'Virement Com'), ('virement_especes', 'Virement / Espèces'), ('especes', 'Espèces'), ('carte', 'Carte bancaire'), ('virement', 'Par virement (Ancien)'), ('cheque', 'Par chèque'), ('agence', "À l'agence"), ('sur_place', 'Sur place')], max_length=30),
        ),
    ]
