# Generated by Django 6.0.3 on 2026-09-09 11:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_mobile_1', models.CharField(blank=True, default='06 64 22 67 90', max_length=50, verbose_name='Téléphone mobile 1 (affichage)')),
                ('phone_mobile_1_intl', models.CharField(blank=True, default='+212664226790', max_length=50, verbose_name='Téléphone mobile 1 (format appel tel:+212...)')),
                ('phone_mobile_2', models.CharField(blank=True, default='06 64 33 14 63', max_length=50, verbose_name='Téléphone mobile 2 (affichage)')),
                ('phone_mobile_2_intl', models.CharField(blank=True, default='+212664331463', max_length=50, verbose_name='Téléphone mobile 2 (format appel tel:+212...)')),
                ('phone_fixe', models.CharField(blank=True, default='05 22 20 02 39', max_length=50, verbose_name='Téléphone fixe (affichage)')),
                ('phone_fixe_intl', models.CharField(blank=True, default='+212522200177', max_length=50, verbose_name='Téléphone fixe (format appel tel:+212...)')),
                ('whatsapp_number', models.CharField(blank=True, default='+212664331463', max_length=50, verbose_name='Numéro WhatsApp principal (+212...)')),
                ('email_contact', models.EmailField(blank=True, default='contact@agencemenage.ma', max_length=254, verbose_name='Email de contact public')),
                ('email_notifications', models.EmailField(blank=True, default='notification@agencemenage.ma', max_length=254, verbose_name='Email de réception des notifications')),
                ('bureau_casa_label', models.CharField(blank=True, default='Bureau Casablanca', max_length=150, verbose_name='Libellé Bureau Casablanca')),
                ('bureau_casa_address', models.TextField(blank=True, default='36 boulevard d’anfa, résidence Anafe A, etage 7', verbose_name='Adresse Bureau Casablanca')),
                ('bureau_casa_maps_url', models.TextField(blank=True, default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3323.4846067727145!2d-7.6324838!3d33.5932599!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMzPCsDM1JzM1LjciTiA3wrAzNyc1Ni45Ilc!5e0!3m2!1sfr!2sma!4v1635848529285!5m2!1sfr!2sma', verbose_name='URL Google Maps Embed Casablanca')),
                ('bureau_rabat_label', models.CharField(blank=True, default='Bureau Rabat', max_length=150, verbose_name='Libellé Bureau Rabat')),
                ('bureau_rabat_address', models.TextField(blank=True, default='Avenue Hassan II, centre commercial Reda, porte G, appt. 49', verbose_name='Adresse Bureau Rabat')),
                ('bureau_rabat_maps_url', models.TextField(blank=True, default='https://maps.google.com/maps?q=34.020882,-6.836218(Agence%20M%C3%A9nage%20Rabat)&z=15&output=embed', verbose_name='URL Google Maps Embed Rabat')),
                ('facebook_url', models.URLField(blank=True, default='https://www.facebook.com/profile.php?id=61586972460164', max_length=500, verbose_name='Lien Facebook')),
                ('instagram_url', models.URLField(blank=True, default='https://www.instagram.com/agencemenage?igsh=MXBtNmxzNmNwcmdiYg==&utm_source=ig_contact_invite', max_length=500, verbose_name='Lien Instagram')),
                ('tiktok_url', models.CharField(blank=True, default='', max_length=500, verbose_name='Lien TikTok')),
                ('whatsapp_notification_numbers', models.JSONField(blank=True, default=list, verbose_name='Numéros WhatsApp de notification interne')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres du Site',
                'verbose_name_plural': 'Paramètres du Site',
            },
        ),
    ]
